### PR TITLE
Update Proguard Rules for Androidx

### PR DESCRIPTION
**Pull request by iMJ007**
Added Proguard rules required if using Androidx libraires

### CODE REVIEW

**Comment by patrickfav** [comment]
Hi @iMJ007 

Thanks for the PR. Here is my feedback:

1. It is redundant to add the "keep native" methods, as this rule is already present in the default Google Android Proguard rules. See https://android.googlesource.com/platform/sdk/+/master/files/proguard-android.txt

```
 -keepclasseswithmembernames class * {
	native <methods>;
	}
```
2. I think it would be better to add the new rule to the internal library private proguard rule file than just adding this to the readme. See https://github.com/patrickfav/Dali/blob/master/dali/proguard-rules.pro

**Comment by patrickfav** [comment]
Hey @iMJ007 

Just want to check if you are willing to update the PR with my suggestions?

**Comment by iMJ007** [comment]
> Hey @iMJ007
> 
> Just want to check if you are willing to update the PR with my suggestions?

Hello @patrickfav ,

I have updated the Pull Request with suggested changes.

**Comment by patrickfav** [comment]
LGTM.
Thanks for the PR!

**Pull request merged**
